language: python
python:
  - "2.7.15"
install:
  - pip install -r requirements.txt
  - wget https://github.com/filippoferrari/pyDVS/archive/v1.0.tar.gz
  - tar -xzvf v1.0.tar.gz
  - pushd v1.0.tar.gz && python setup.py build_ext --inplace && popd
  - export PYTHONPATH=$PYTHONPATH:$PWD/casperjs-1.0.2/bin/
script:
  - pytest
