language: python

python:
  - "2.7.15"

install:
  - pip install -r requirements.txt
  - pip install opencv-python 
  - wget https://github.com/filippoferrari/pyDVS/archive/v1.0.tar.gz -O ~/pyDVS.tar.gz
  - tar -xzvf ~/pyDVS.tar.gz
  - pushd ~/pyDVS && python setup.py build_ext --inplace && popd
  - export PYTHONPATH=$PYTHONPATH:~/pyDVS/

# before_script:
#   - echo '[Machine]' > ~/.spynnaker.cfg
#   - echo "machineName = $SPINNAKER_BOARD_ADDRESS" >> ~/.spynnaker.cfg
#   - echo "version = ${SPINNAKER_BOARD_VERSION:-5}" >> ~/.spynnaker.cfg
#   - echo '[Database]' >> ~/.spynnaker.cfg
#   - echo '[Simulation]' >> ~/.spynnaker.cfg
#   - echo '[Buffers]' >> ~/.spynnaker.cfg

script:
  - pytest
